version: "3.8"
services:
  app:
    container_name: backend_takehome
    build: ./
    depends_on:
      - db
    ports:
      - "8000:5000"
    networks:
      - app-network
    restart: always

  db:
    container_name: db
    image: 'postgres:latest'
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge